import fs from "fs";
import path from "path";
import Link from "next/link";

export default function home({ data }) {
  return (
    <div>
      <h1>napari plugins</h1>
      <p>This page serves the REST API for napari plugins.</p>
      <p>It is generated by the source code in the <Link href={"https://github.com/napari/npe2api"}>npe2api repo</Link>.</p>
      <p>A user-friendly site for napari plugin information is <Link href={`https://napari-hub.org/`}>napari-hub.org</Link></p>
      <h3>Commonly used API endpoints</h3>
      <p>Plugin index: <Link href={`/api/plugins`}>/api/plugins</Link></p>
      <p>Summary info: <Link href={`/api/extended_summary`}>/api/extended_summary</Link></p>
      <p>PyPI information: Use <code>/api/pypi/pypi_plugin_name</code> endpoint for an individual plugin.</p>
      <p>Conda index: <Link href={`/api/conda`}>/api/conda</Link>  (see conda info for each plugin at /api/conda/pypi_name)</p>
      <p>Fetch errors: <Link href={`/errors.json`}>errors.json</Link></p>
      <h3>Plugin manifests</h3>
      <ul>
        {data.map((item) => (
          <li key={item.name}>
            <Link
              as={`/api/manifest/${item.name}`}
              href={`/api/manifest/[slug]`}
            >

              {item.name}-{item.version}

            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export const getStaticProps = async () => {
  const source = fs.readFileSync(
    path.join(process.cwd(), "public", "index.json")
  );
  const index = JSON.parse(source);
  // Convert index object to array with just name and version
  const data = Object.entries(index).map(([name, version]) => ({
    name,
    version,
  }));
  return {
    props: {
      data,
    },
  };
};
