"""Generate index.html dynamically for the root path."""

import json


async def generate_index_html(env) -> str:
    """
    Generate a simple index.html page listing all plugins.

    Args:
        env: The worker environment with BUCKET binding

    Returns:
        HTML string
    """
    # index.json contains the plugin list
    obj = await env.BUCKET.get("index.json")

    if not obj:
        return FALLBACK_HTML

    content = await obj.text()
    index_data = json.loads(content)

    plugin_list_html = "\n".join(
        [
            f'  <li><a href="api/manifest/{name}">{name}-{version}</a></li>'
            for name, version in sorted(index_data.items())
        ]
    )

    return PLUGIN_LIST_HTML.format(plugin_list_html=plugin_list_html)


PLUGIN_LIST_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>napari plugins</title>
</head>
<body>
    <div>
        <h1>napari plugins</h1>
        <p>This page serves the REST API for napari plugins.</p>
        <p>
            It is generated by the source code in the
            <a href="https://github.com/napari/npe2api">npe2api repo</a>.
        </p>
        <p>
            A user-friendly site for napari plugin information is
            <a href="https://napari-hub.org/">napari-hub.org</a>
        </p>
        <h3>Commonly used API endpoints</h3>
        <p>Plugin index: <a href="api/plugins">api/plugins</a></p>
        <p>
            Summary info:
                <a href="api/extended_summary">api/extended_summary</a>
        </p>
        <p>
            PyPI information:
                Use <code>api/pypi/pypi_plugin_name</code>
                endpoint for an individual plugin.
        </p>
        <p>
            Conda index: <a href="api/conda">api/conda</a>
            (see conda info for each plugin at api/conda/pypi_name)
        </p>
        <p>Fetch errors: <a href="errors.json">errors.json</a></p>
        <h3>Plugin manifests</h3>
        <ul>
        {plugin_list_html}
        </ul>
    </div>
</body>
</html>
"""

FALLBACK_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>napari plugins</title>
</head>
<body>
    <h1>napari plugins</h1>
    <p><strong>⚠️ There's been a problem loading the plugin index.</strong></p>
    <p>
        If this problem persists, please
        <a href="https://github.com/napari/npe2api/issues">report it on GitHub</a>.
    </p>
    <p>This page serves the REST API for napari plugins.</p>
    <p>
        It is generated by the source code in the
        <a href="https://github.com/napari/npe2api">npe2api repo</a>.
    </p>
    <p>
        A user-friendly site for napari plugin information is
        <a href="https://napari-hub.org/">napari-hub.org</a>
    </p>
</body>
</html>
"""
