name: Fetch manifests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # “Every 10 minutes”
    - cron: "*/10 * * * *"

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      # use `npe2 fetch -all` to fetch all plugin manifests into the public/manifest folder
      - name: fetch manifests
        run: |
          python -m pip install -U pip
          python -m pip install git+https://github.com/napari/npe2.git
          python -m pip install -r requirements.txt
          npe2 fetch --all -o public/manifest

      # validate and index manifests into easily searchable json files
      - name: index and validate
        run: |
          python scripts/reindex.py
          python scripts/validate.py
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          CODECOV_API_TOKEN: ${{ secrets.CODECOV_API_TOKEN }}

      # push changes back to the repo, this will trigger a new vercel build
      # https://github.com/stefanzweifel/git-auto-commit-action
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event_name != 'pull_request'
        with:
          commit_message: Update manifests
